image: node:latest

stages:
  - install
  - build
  - publish

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

cache:
  paths:
    - '**/node_modules/'

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  needs: [install]
  script:
    - npm run build
  artifacts:
    paths:
      - packages/*/dist

.publish_template: &publish_job
  stage: publish
  needs: [build]
  script:
    - echo "@pdfme:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm config set @pdfme:registry ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
    - npm publish --registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
  only:
    - main

publish_common:
  <<: *publish_job
  variables:
    PACKAGE_PATH: packages/common
  before_script:
    - cd ${PACKAGE_PATH}

publish_generator:
  <<: *publish_job
  variables:
    PACKAGE_PATH: packages/generator
  before_script:
    - cd ${PACKAGE_PATH}

publish_form:
  <<: *publish_job
  variables:
    PACKAGE_PATH: packages/form
  before_script:
    - cd ${PACKAGE_PATH}

publish_ui:
  <<: *publish_job
  variables:
    PACKAGE_PATH: packages/ui
  before_script:
    - cd ${PACKAGE_PATH}