image: node:latest

cache:
  paths:
    - '**/node_modules/'

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - packages/*/dist/  # Adjust this path based on your project structure

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r packages/*/dist/* public/  # Adjust this based on which packages you want to deploy
  artifacts:
    paths:
      - public
  only:
    - main  # This job will only run on the main branch